name = "stratnex-consulting"
compatibility_date = "2025-01-27"
pages_build_output_dir = "dist"

[build]
command = "npm run build:pages"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200